#![allow(dead_code)]

pub enum Opcode {
    // Constants
    Nop,
    AconstNull,
    IconstM1,
    Iconst0,
    Iconst1,
    Iconst2,
    Iconst3,
    Iconst4,
    Iconst5,
    Lconst0,
    Lconst1,
    Fconst0,
    Fconst1,
    Fconst2,
    Dconst0,
    Dconst1,
    Bipush,
    Sipush,
    Ldc,
    LdcW,
    Ldc2W,
    // Loads
    Iload,
    Lload,
    Fload,
    Dload,
    Aload,
    Iload0,
    Iload1,
    Iload2,
    Iload3,
    Lload0,
    Lload1,
    Lload2,
    Lload3,
    Fload0,
    Fload1,
    Fload2,
    Fload3,
    Dload0,
    Dload1,
    Dload2,
    Dload3,
    Aload0,
    Aload1,
    Aload2,
    Aload3,
    Iaload,
    Laload,
    Faload,
    Daload,
    Aaload,
    Baload,
    Caload,
    Saload,
    // Stores
    Istore,
    Lstore,
    Fstore,
    Dstore,
    Astore,
    Istore0,
    Istore1,
    Istore2,
    Istore3,
    Lstore0,
    Lstore1,
    Lstore2,
    Lstore3,
    Fstore0,
    Fstore1,
    Fstore2,
    Fstore3,
    Dstore0,
    Dstore1,
    Dstore2,
    Dstore3,
    Astore0,
    Astore1,
    Astore2,
    Astore3,
    Iastore,
    Lastore,
    Fastore,
    Dastore,
    Aastore,
    Bastore,
    Castore,
    Sastore,
    // Stack
    Pop,
    Pop2,
    Dup,
    DupX1,
    DupX2,
    Dup2,
    Dup2X1,
    Dup2X2,
    Swap,
    // Math
    Iadd,
    Ladd,
    Fadd,
    Dadd,
    Isub,
    Lsub,
    Fsub,
    Dsub,
    Imul,
    Lmul,
    Fmul,
    Dmul,
    Idiv,
    Ldiv,
    Fdiv,
    Ddiv,
    Irem,
    Lrem,
    Frem,
    Drem,
    Ineg,
    Lneg,
    Fneg,
    Dneg,
    Ishl,
    Lshl,
    Ishr,
    Lshr,
    Iushr,
    Lushr,
    Iand,
    Land,
    Ior,
    Lor,
    Ixor,
    Lxor,
    Iinc,
    // Conversions
    I2l,
    I2f,
    I2d,
    L2i,
    L2f,
    L2d,
    F2i,
    F2l,
    F2d,
    D2i,
    D2l,
    D2f,
    I2b,
    I2c,
    I2s,
    // Comparisons
    Lcmp,
    Fcmpl,
    Fcmpg,
    Dcmpl,
    Dcmpg,
    Ifeq,
    Ifne,
    Iflt,
    Ifge,
    Ifgt,
    Ifle,
    IfIcmpeq,
    IfIcmpne,
    IfIcmplt,
    IfIcmpge,
    IfIcmpgt,
    IfIcmple,
    IfAcmpeq,
    IfAcmpne,
    // Control
    Goto,
    Jsr,
    Ret,
    Tableswitch,
    Lookupswitch,
    Ireturn,
    Lreturn,
    Freturn,
    Dreturn,
    Areturn,
    Return,
    // References
    Getstatic,
    Putstatic,
    Getfield,
    Putfield,
    Invokevirtual,
    Invokespecial,
    Invokestatic,
    Invokeinterface,
    Invokedynamic,
    New,
    Newarray,
    Anewarray,
    Arraylength,
    Athrow,
    Checkcast,
    Instanceof,
    Monitorenter,
    Monitorexit,
    // Extended
    Wide,
    Multianewarray,
    Ifnull,
    Ifnonnull,
    GotoW,
    JsrW,
    // Reserved
    Breakpoint,
    Impdep1,
    Impdep2,
}

impl Opcode {
    pub fn value(&self) -> u8 {
        match &self {
            // Constants
            Opcode::Nop => 00,
            Opcode::AconstNull => 01,
            Opcode::IconstM1 => 02,
            Opcode::Iconst0 => 03,
            Opcode::Iconst1 => 04,
            Opcode::Iconst2 => 05,
            Opcode::Iconst3 => 06,
            Opcode::Iconst4 => 07,
            Opcode::Iconst5 => 08,
            Opcode::Lconst0 => 09,
            Opcode::Lconst1 => 10,
            Opcode::Fconst0 => 11,
            Opcode::Fconst1 => 12,
            Opcode::Fconst2 => 13,
            Opcode::Dconst0 => 14,
            Opcode::Dconst1 => 15,
            Opcode::Bipush => 16,
            Opcode::Sipush => 17,
            Opcode::Ldc => 18,
            Opcode::LdcW => 19,
            Opcode::Ldc2W => 20,
            // Loads
            Opcode::Iload => 21,
            Opcode::Lload => 22,
            Opcode::Fload => 23,
            Opcode::Dload => 24,
            Opcode::Aload => 25,
            Opcode::Iload0 => 26,
            Opcode::Iload1 => 27,
            Opcode::Iload2 => 28,
            Opcode::Iload3 => 29,
            Opcode::Lload0 => 30,
            Opcode::Lload1 => 31,
            Opcode::Lload2 => 32,
            Opcode::Lload3 => 33,
            Opcode::Fload0 => 34,
            Opcode::Fload1 => 35,
            Opcode::Fload2 => 36,
            Opcode::Fload3 => 37,
            Opcode::Dload0 => 38,
            Opcode::Dload1 => 39,
            Opcode::Dload2 => 40,
            Opcode::Dload3 => 41,
            Opcode::Aload0 => 42,
            Opcode::Aload1 => 43,
            Opcode::Aload2 => 44,
            Opcode::Aload3 => 45,
            Opcode::Iaload => 46,
            Opcode::Laload => 47,
            Opcode::Faload => 48,
            Opcode::Daload => 49,
            Opcode::Aaload => 50,
            Opcode::Baload => 51,
            Opcode::Caload => 52,
            Opcode::Saload => 53,
            // Stores
            Opcode::Istore => 54,
            Opcode::Lstore => 55,
            Opcode::Fstore => 56,
            Opcode::Dstore => 57,
            Opcode::Astore => 58,
            Opcode::Istore0 => 59,
            Opcode::Istore1 => 60,
            Opcode::Istore2 => 61,
            Opcode::Istore3 => 62,
            Opcode::Lstore0 => 63,
            Opcode::Lstore1 => 64,
            Opcode::Lstore2 => 65,
            Opcode::Lstore3 => 66,
            Opcode::Fstore0 => 67,
            Opcode::Fstore1 => 68,
            Opcode::Fstore2 => 69,
            Opcode::Fstore3 => 70,
            Opcode::Dstore0 => 71,
            Opcode::Dstore1 => 72,
            Opcode::Dstore2 => 73,
            Opcode::Dstore3 => 74,
            Opcode::Astore0 => 75,
            Opcode::Astore1 => 76,
            Opcode::Astore2 => 77,
            Opcode::Astore3 => 78,
            Opcode::Iastore => 79,
            Opcode::Lastore => 80,
            Opcode::Fastore => 81,
            Opcode::Dastore => 82,
            Opcode::Aastore => 83,
            Opcode::Bastore => 84,
            Opcode::Castore => 85,
            Opcode::Sastore => 86,
            // Stack
            Opcode::Pop => 87,
            Opcode::Pop2 => 88,
            Opcode::Dup => 89,
            Opcode::DupX1 => 90,
            Opcode::DupX2 => 91,
            Opcode::Dup2 => 92,
            Opcode::Dup2X1 => 93,
            Opcode::Dup2X2 => 94,
            Opcode::Swap => 95,
            // Math
            Opcode::Iadd => 96,
            Opcode::Ladd => 97,
            Opcode::Fadd => 98,
            Opcode::Dadd => 99,
            Opcode::Isub => 100,
            Opcode::Lsub => 101,
            Opcode::Fsub => 102,
            Opcode::Dsub => 103,
            Opcode::Imul => 104,
            Opcode::Lmul => 105,
            Opcode::Fmul => 106,
            Opcode::Dmul => 107,
            Opcode::Idiv => 108,
            Opcode::Ldiv => 109,
            Opcode::Fdiv => 110,
            Opcode::Ddiv => 111,
            Opcode::Irem => 112,
            Opcode::Lrem => 113,
            Opcode::Frem => 114,
            Opcode::Drem => 115,
            Opcode::Ineg => 116,
            Opcode::Lneg => 117,
            Opcode::Fneg => 118,
            Opcode::Dneg => 119,
            Opcode::Ishl => 120,
            Opcode::Lshl => 121,
            Opcode::Ishr => 122,
            Opcode::Lshr => 123,
            Opcode::Iushr => 124,
            Opcode::Lushr => 125,
            Opcode::Iand => 126,
            Opcode::Land => 127,
            Opcode::Ior => 128,
            Opcode::Lor => 129,
            Opcode::Ixor => 130,
            Opcode::Lxor => 131,
            Opcode::Iinc => 132,
            // Conversions
            Opcode::I2l => 133,
            Opcode::I2f => 134,
            Opcode::I2d => 135,
            Opcode::L2i => 136,
            Opcode::L2f => 137,
            Opcode::L2d => 138,
            Opcode::F2i => 139,
            Opcode::F2l => 140,
            Opcode::F2d => 141,
            Opcode::D2i => 142,
            Opcode::D2l => 143,
            Opcode::D2f => 144,
            Opcode::I2b => 145,
            Opcode::I2c => 146,
            Opcode::I2s => 147,
            // Comparisons
            Opcode::Lcmp => 148,
            Opcode::Fcmpl => 149,
            Opcode::Fcmpg => 150,
            Opcode::Dcmpl => 151,
            Opcode::Dcmpg => 152,
            Opcode::Ifeq => 153,
            Opcode::Ifne => 154,
            Opcode::Iflt => 155,
            Opcode::Ifge => 156,
            Opcode::Ifgt => 157,
            Opcode::Ifle => 158,
            Opcode::IfIcmpeq => 159,
            Opcode::IfIcmpne => 160,
            Opcode::IfIcmplt => 161,
            Opcode::IfIcmpge => 162,
            Opcode::IfIcmpgt => 163,
            Opcode::IfIcmple => 164,
            Opcode::IfAcmpeq => 165,
            Opcode::IfAcmpne => 166,
            // Control
            Opcode::Goto => 167,
            Opcode::Jsr => 168,
            Opcode::Ret => 169,
            Opcode::Tableswitch => 170,
            Opcode::Lookupswitch => 171,
            Opcode::Ireturn => 172,
            Opcode::Lreturn => 173,
            Opcode::Freturn => 174,
            Opcode::Dreturn => 175,
            Opcode::Areturn => 176,
            Opcode::Return => 177,
            // References
            Opcode::Getstatic => 178,
            Opcode::Putstatic => 179,
            Opcode::Getfield => 180,
            Opcode::Putfield => 181,
            Opcode::Invokevirtual => 182,
            Opcode::Invokespecial => 183,
            Opcode::Invokestatic => 184,
            Opcode::Invokeinterface => 185,
            Opcode::Invokedynamic => 186,
            Opcode::New => 187,
            Opcode::Newarray => 188,
            Opcode::Anewarray => 189,
            Opcode::Arraylength => 190,
            Opcode::Athrow => 191,
            Opcode::Checkcast => 192,
            Opcode::Instanceof => 193,
            Opcode::Monitorenter => 194,
            Opcode::Monitorexit => 195,
            // Extended
            Opcode::Wide => 196,
            Opcode::Multianewarray => 197,
            Opcode::Ifnull => 198,
            Opcode::Ifnonnull => 199,
            Opcode::GotoW => 200,
            Opcode::JsrW => 201,
            // Reserved
            Opcode::Breakpoint => 202,
            Opcode::Impdep1 => 254,
            Opcode::Impdep2 => 255,
        }
    }

    pub fn str(&self) -> &str {
        match &self {
            // Constants
            Opcode::Nop => "nop",
            Opcode::AconstNull => "aconst_null",
            Opcode::IconstM1 => "iconst_m1",
            Opcode::Iconst0 => "iconst_0",
            Opcode::Iconst1 => "iconst_1",
            Opcode::Iconst2 => "iconst_2",
            Opcode::Iconst3 => "iconst_3",
            Opcode::Iconst4 => "iconst_4",
            Opcode::Iconst5 => "iconst_5",
            Opcode::Lconst0 => "lconst_0",
            Opcode::Lconst1 => "lconst_1",
            Opcode::Fconst0 => "fconst_0",
            Opcode::Fconst1 => "fconst_1",
            Opcode::Fconst2 => "fconst_2",
            Opcode::Dconst0 => "dconst_0",
            Opcode::Dconst1 => "dconst_1",
            Opcode::Bipush => "bipush",
            Opcode::Sipush => "sipush",
            Opcode::Ldc => "ldc",
            Opcode::LdcW => "ldc_w",
            Opcode::Ldc2W => "ldc2_w",
            // Loads
            Opcode::Iload => "iload",
            Opcode::Lload => "lload",
            Opcode::Fload => "fload",
            Opcode::Dload => "dload",
            Opcode::Aload => "aload",
            Opcode::Iload0 => "iload_0",
            Opcode::Iload1 => "iload_1",
            Opcode::Iload2 => "iload_2",
            Opcode::Iload3 => "iload_3",
            Opcode::Lload0 => "lload_0",
            Opcode::Lload1 => "lload_1",
            Opcode::Lload2 => "lload_2",
            Opcode::Lload3 => "lload_3",
            Opcode::Fload0 => "fload_0",
            Opcode::Fload1 => "fload_1",
            Opcode::Fload2 => "fload_2",
            Opcode::Fload3 => "fload_3",
            Opcode::Dload0 => "dload_0",
            Opcode::Dload1 => "dload_1",
            Opcode::Dload2 => "dload_2",
            Opcode::Dload3 => "dload_3",
            Opcode::Aload0 => "aload_0",
            Opcode::Aload1 => "aload_1",
            Opcode::Aload2 => "aload_2",
            Opcode::Aload3 => "aload_3",
            Opcode::Iaload => "iaload",
            Opcode::Laload => "laload",
            Opcode::Faload => "faload",
            Opcode::Daload => "daload",
            Opcode::Aaload => "aaload",
            Opcode::Baload => "baload",
            Opcode::Caload => "caload",
            Opcode::Saload => "saload",
            // Stores
            Opcode::Istore => "istore",
            Opcode::Lstore => "lstore",
            Opcode::Fstore => "fstore",
            Opcode::Dstore => "dstore",
            Opcode::Astore => "astore",
            Opcode::Istore0 => "istore_0",
            Opcode::Istore1 => "istore_1",
            Opcode::Istore2 => "istore_2",
            Opcode::Istore3 => "istore_3",
            Opcode::Lstore0 => "lstore_0",
            Opcode::Lstore1 => "lstore_1",
            Opcode::Lstore2 => "lstore_2",
            Opcode::Lstore3 => "lstore_3",
            Opcode::Fstore0 => "fstore_0",
            Opcode::Fstore1 => "fstore_1",
            Opcode::Fstore2 => "fstore_2",
            Opcode::Fstore3 => "fstore_3",
            Opcode::Dstore0 => "dstore_0",
            Opcode::Dstore1 => "dstore_1",
            Opcode::Dstore2 => "dstore_2",
            Opcode::Dstore3 => "dstore_3",
            Opcode::Astore0 => "astore_0",
            Opcode::Astore1 => "astore_1",
            Opcode::Astore2 => "astore_2",
            Opcode::Astore3 => "astore_3",
            Opcode::Iastore => "iastore",
            Opcode::Lastore => "lastore",
            Opcode::Fastore => "fastore",
            Opcode::Dastore => "dastore",
            Opcode::Aastore => "aastore",
            Opcode::Bastore => "bastore",
            Opcode::Castore => "castore",
            Opcode::Sastore => "sastore",
            // Stack
            Opcode::Pop => "pop",
            Opcode::Pop2 => "pop2",
            Opcode::Dup => "dup",
            Opcode::DupX1 => "dup_x1",
            Opcode::DupX2 => "dup_x2",
            Opcode::Dup2 => "dup2",
            Opcode::Dup2X1 => "dup2_x1",
            Opcode::Dup2X2 => "dup2_x2",
            Opcode::Swap => "swap",
            // Math
            Opcode::Iadd => "iadd",
            Opcode::Ladd => "ladd",
            Opcode::Fadd => "fadd",
            Opcode::Dadd => "dadd",
            Opcode::Isub => "isub",
            Opcode::Lsub => "lsub",
            Opcode::Fsub => "fsub",
            Opcode::Dsub => "dsub",
            Opcode::Imul => "imul",
            Opcode::Lmul => "lmul",
            Opcode::Fmul => "fmul",
            Opcode::Dmul => "dmul",
            Opcode::Idiv => "idiv",
            Opcode::Ldiv => "ldiv",
            Opcode::Fdiv => "fdiv",
            Opcode::Ddiv => "ddiv",
            Opcode::Irem => "irem",
            Opcode::Lrem => "lrem",
            Opcode::Frem => "frem",
            Opcode::Drem => "drem",
            Opcode::Ineg => "ineg",
            Opcode::Lneg => "lneg",
            Opcode::Fneg => "fneg",
            Opcode::Dneg => "dneg",
            Opcode::Ishl => "ishl",
            Opcode::Lshl => "lshl",
            Opcode::Ishr => "ishr",
            Opcode::Lshr => "lshr",
            Opcode::Iushr => "iushr",
            Opcode::Lushr => "lushr",
            Opcode::Iand => "iand",
            Opcode::Land => "land",
            Opcode::Ior => "ior",
            Opcode::Lor => "lor",
            Opcode::Ixor => "ixor",
            Opcode::Lxor => "lxor",
            Opcode::Iinc => "iinc",
            // Conversions
            Opcode::I2l => "i2l",
            Opcode::I2f => "i2f",
            Opcode::I2d => "i2d",
            Opcode::L2i => "l2i",
            Opcode::L2f => "l2f",
            Opcode::L2d => "l2d",
            Opcode::F2i => "f2i",
            Opcode::F2l => "f2l",
            Opcode::F2d => "f2d",
            Opcode::D2i => "d2i",
            Opcode::D2l => "d2l",
            Opcode::D2f => "d2f",
            Opcode::I2b => "i2b",
            Opcode::I2c => "i2c",
            Opcode::I2s => "i2s",
            // Comparisons
            Opcode::Lcmp => "lcmp",
            Opcode::Fcmpl => "fcmpl",
            Opcode::Fcmpg => "fcmpg",
            Opcode::Dcmpl => "dcmpl",
            Opcode::Dcmpg => "dcmpg",
            Opcode::Ifeq => "ifeq",
            Opcode::Ifne => "ifne",
            Opcode::Iflt => "iflt",
            Opcode::Ifge => "ifge",
            Opcode::Ifgt => "ifgt",
            Opcode::Ifle => "ifle",
            Opcode::IfIcmpeq => "if_icmpeq",
            Opcode::IfIcmpne => "if_icmpne",
            Opcode::IfIcmplt => "if_icmplt",
            Opcode::IfIcmpge => "if_icmpge",
            Opcode::IfIcmpgt => "if_icmpgt",
            Opcode::IfIcmple => "if_icmple",
            Opcode::IfAcmpeq => "if_acmpeq",
            Opcode::IfAcmpne => "if_acmpne",
            // Control
            Opcode::Goto => "goto",
            Opcode::Jsr => "jsr",
            Opcode::Ret => "ret",
            Opcode::Tableswitch => "tableswitch",
            Opcode::Lookupswitch => "lookupswitch",
            Opcode::Ireturn => "ireturn",
            Opcode::Lreturn => "lreturn",
            Opcode::Freturn => "freturn",
            Opcode::Dreturn => "dreturn",
            Opcode::Areturn => "areturn",
            Opcode::Return => "return",
            // References
            Opcode::Getstatic => "getstatic",
            Opcode::Putstatic => "putstatic",
            Opcode::Getfield => "getfield",
            Opcode::Putfield => "putfield",
            Opcode::Invokevirtual => "invokevirtual",
            Opcode::Invokespecial => "invokespecial",
            Opcode::Invokestatic => "invokestatic",
            Opcode::Invokeinterface => "invokeinterface",
            Opcode::Invokedynamic => "invokedynamic",
            Opcode::New => "new",
            Opcode::Newarray => "newarray",
            Opcode::Anewarray => "anewarray",
            Opcode::Arraylength => "arraylength",
            Opcode::Athrow => "athrow",
            Opcode::Checkcast => "checkcast",
            Opcode::Instanceof => "instanceof",
            Opcode::Monitorenter => "monitorenter",
            Opcode::Monitorexit => "monitorexit",
            // Extended
            Opcode::Wide => "wide",
            Opcode::Multianewarray => "multianewarray",
            Opcode::Ifnull => "ifnull",
            Opcode::Ifnonnull => "ifnonnull",
            Opcode::GotoW => "goto_w",
            Opcode::JsrW => "jsr_w",
            // Reserved
            Opcode::Breakpoint => "breakpoint",
            Opcode::Impdep1 => "impdep1",
            Opcode::Impdep2 => "impdep2",
        }
    }
}

pub fn get_opcode(opcode: u8) -> Opcode {
    match opcode {
        // Constants
        00 => Opcode::Nop,
        01 => Opcode::AconstNull,
        02 => Opcode::IconstM1,
        03 => Opcode::Iconst0,
        04 => Opcode::Iconst1,
        05 => Opcode::Iconst2,
        06 => Opcode::Iconst3,
        07 => Opcode::Iconst4,
        08 => Opcode::Iconst5,
        09 => Opcode::Lconst0,
        10 => Opcode::Lconst1,
        11 => Opcode::Fconst0,
        12 => Opcode::Fconst1,
        13 => Opcode::Fconst2,
        14 => Opcode::Dconst0,
        15 => Opcode::Dconst1,
        16 => Opcode::Bipush,
        17 => Opcode::Sipush,
        18 => Opcode::Ldc,
        19 => Opcode::LdcW,
        20 => Opcode::Ldc2W,
        // Loads
        21 => Opcode::Iload,
        22 => Opcode::Lload,
        23 => Opcode::Fload,
        24 => Opcode::Dload,
        25 => Opcode::Aload,
        26 => Opcode::Iload0,
        27 => Opcode::Iload1,
        28 => Opcode::Iload2,
        29 => Opcode::Iload3,
        30 => Opcode::Lload0,
        31 => Opcode::Lload1,
        32 => Opcode::Lload2,
        33 => Opcode::Lload3,
        34 => Opcode::Fload0,
        35 => Opcode::Fload1,
        36 => Opcode::Fload2,
        37 => Opcode::Fload3,
        38 => Opcode::Dload0,
        39 => Opcode::Dload1,
        40 => Opcode::Dload2,
        41 => Opcode::Dload3,
        42 => Opcode::Aload0,
        43 => Opcode::Aload1,
        44 => Opcode::Aload2,
        45 => Opcode::Aload3,
        46 => Opcode::Iaload,
        47 => Opcode::Laload,
        48 => Opcode::Faload,
        49 => Opcode::Daload,
        50 => Opcode::Aaload,
        51 => Opcode::Baload,
        52 => Opcode::Caload,
        53 => Opcode::Saload,
        // Stores
        54 => Opcode::Istore,
        55 => Opcode::Lstore,
        56 => Opcode::Fstore,
        57 => Opcode::Dstore,
        58 => Opcode::Astore,
        59 => Opcode::Istore0,
        60 => Opcode::Istore1,
        61 => Opcode::Istore2,
        62 => Opcode::Istore3,
        63 => Opcode::Lstore0,
        64 => Opcode::Lstore1,
        65 => Opcode::Lstore2,
        66 => Opcode::Lstore3,
        67 => Opcode::Fstore0,
        68 => Opcode::Fstore1,
        69 => Opcode::Fstore2,
        70 => Opcode::Fstore3,
        71 => Opcode::Dstore0,
        72 => Opcode::Dstore1,
        73 => Opcode::Dstore2,
        74 => Opcode::Dstore3,
        75 => Opcode::Astore0,
        76 => Opcode::Astore1,
        77 => Opcode::Astore2,
        78 => Opcode::Astore3,
        79 => Opcode::Iastore,
        80 => Opcode::Lastore,
        81 => Opcode::Fastore,
        82 => Opcode::Dastore,
        83 => Opcode::Aastore,
        84 => Opcode::Bastore,
        85 => Opcode::Castore,
        86 => Opcode::Sastore,
        // Stack
        87 => Opcode::Pop,
        88 => Opcode::Pop2,
        89 => Opcode::Dup,
        90 => Opcode::DupX1,
        91 => Opcode::DupX2,
        92 => Opcode::Dup2,
        93 => Opcode::Dup2X1,
        94 => Opcode::Dup2X2,
        95 => Opcode::Swap,
        // Math
        96 => Opcode::Iadd,
        97 => Opcode::Ladd,
        98 => Opcode::Fadd,
        99 => Opcode::Dadd,
        100 => Opcode::Isub,
        101 => Opcode::Lsub,
        102 => Opcode::Fsub,
        103 => Opcode::Dsub,
        104 => Opcode::Imul,
        105 => Opcode::Lmul,
        106 => Opcode::Fmul,
        107 => Opcode::Dmul,
        108 => Opcode::Idiv,
        109 => Opcode::Ldiv,
        110 => Opcode::Fdiv,
        111 => Opcode::Ddiv,
        112 => Opcode::Irem,
        113 => Opcode::Lrem,
        114 => Opcode::Frem,
        115 => Opcode::Drem,
        116 => Opcode::Ineg,
        117 => Opcode::Lneg,
        118 => Opcode::Fneg,
        119 => Opcode::Dneg,
        120 => Opcode::Ishl,
        121 => Opcode::Lshl,
        122 => Opcode::Ishr,
        123 => Opcode::Lshr,
        124 => Opcode::Iushr,
        125 => Opcode::Lushr,
        126 => Opcode::Iand,
        127 => Opcode::Land,
        128 => Opcode::Ior,
        129 => Opcode::Lor,
        130 => Opcode::Ixor,
        131 => Opcode::Lxor,
        132 => Opcode::Iinc,
        // Conversions
        133 => Opcode::I2l,
        134 => Opcode::I2f,
        135 => Opcode::I2d,
        136 => Opcode::L2i,
        137 => Opcode::L2f,
        138 => Opcode::L2d,
        139 => Opcode::F2i,
        140 => Opcode::F2l,
        141 => Opcode::F2d,
        142 => Opcode::D2i,
        143 => Opcode::D2l,
        144 => Opcode::D2f,
        145 => Opcode::I2b,
        146 => Opcode::I2c,
        147 => Opcode::I2s,
        // Comparisons
        148 => Opcode::Lcmp,
        149 => Opcode::Fcmpl,
        150 => Opcode::Fcmpg,
        151 => Opcode::Dcmpl,
        152 => Opcode::Dcmpg,
        153 => Opcode::Ifeq,
        154 => Opcode::Ifne,
        155 => Opcode::Iflt,
        156 => Opcode::Ifge,
        157 => Opcode::Ifgt,
        158 => Opcode::Ifle,
        159 => Opcode::IfIcmpeq,
        160 => Opcode::IfIcmpne,
        161 => Opcode::IfIcmplt,
        162 => Opcode::IfIcmpge,
        163 => Opcode::IfIcmpgt,
        164 => Opcode::IfIcmple,
        165 => Opcode::IfAcmpeq,
        166 => Opcode::IfAcmpne,
        // Control
        167 => Opcode::Goto,
        168 => Opcode::Jsr,
        169 => Opcode::Ret,
        170 => Opcode::Tableswitch,
        171 => Opcode::Lookupswitch,
        172 => Opcode::Ireturn,
        173 => Opcode::Lreturn,
        174 => Opcode::Freturn,
        175 => Opcode::Dreturn,
        176 => Opcode::Areturn,
        177 => Opcode::Return,
        // References
        178 => Opcode::Getstatic,
        179 => Opcode::Putstatic,
        180 => Opcode::Getfield,
        181 => Opcode::Putfield,
        182 => Opcode::Invokevirtual,
        183 => Opcode::Invokespecial,
        184 => Opcode::Invokestatic,
        185 => Opcode::Invokeinterface,
        186 => Opcode::Invokedynamic,
        187 => Opcode::New,
        188 => Opcode::Newarray,
        189 => Opcode::Anewarray,
        190 => Opcode::Arraylength,
        191 => Opcode::Athrow,
        192 => Opcode::Checkcast,
        193 => Opcode::Instanceof,
        194 => Opcode::Monitorenter,
        195 => Opcode::Monitorexit,
        // Extended
        196 => Opcode::Wide,
        197 => Opcode::Multianewarray,
        198 => Opcode::Ifnull,
        199 => Opcode::Ifnonnull,
        200 => Opcode::GotoW,
        201 => Opcode::JsrW,
        // Reserved
        202 => Opcode::Breakpoint,
        254 => Opcode::Impdep1,
        255 => Opcode::Impdep2,
        _ => panic!("Invalid opcode {}", opcode)
    }
}